openapi: 3.0.1
info:
  title: Auth service
  description: Сервис авторизации
  version: v0.1.0
servers:
- url: http://localhost:8070
  description: Generated server url
tags:
- name: actions
  description: API для работы с действиями
- name: space-group-roles
  description: API для работы со связями Space-Group-Role
- name: space-types
  description: API для работы с типами пространствами
- name: spaces
  description: API для работы с пространствами
- name: Users
  description: Работа с пользователями
- name: roles
  description: API для работы с ролями
- name: Sync
  description: Синхронизация сервиса с различными источниками
paths:
  /api/v1/spaces/{id}:
    put:
      tags:
      - spaces
      summary: Сохранить пространство
      operationId: saveSpace
      parameters:
      - name: id
        in: path
        description: Идентификатор пространства
        required: true
        schema:
          type: string
        example: PPCH_PUB
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Space_Save'
        required: true
      responses:
        "401":
          description: Unauthorized
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'
